### ISSUE TITLE
Informacion sobre tabla de grupos

### ISSUE THREAD

**Issue by Bound3R** [Axiacore/CopaDev#28]
Hola, veo que esta la tabla de grupos, pero cuales son los equipos A, B, C...? 
#### Grupo A

| Equipos | Pts | PG | PE | PP | GF | GC | DF |
| --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| Equipo A | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Equipo B | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Equipo C | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Equipo D | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

**Comment by sanfeijoo** [comment]
Hola, ya hicimos el sorteo de que equipo es cual. Ya enviamos subimos el video.
