### ISSUE TITLE
URL .io/copadev en minuscula retorna 404

### ISSUE THREAD

**Issue by PabloVallejo** [Axiacore/CopaDev#8]
Esta url retorna 404 http://edunext.github.io/copadev/

No se si sea buena idea cambiar el nombre del repositorio para que quede en minuscula.

Que opinan @felipemontoya @Bound3R?

**Comment by felipemontoya** [comment]
Depende de si ya hay links que apunten a http://edunext.github.io/CopaDev/ y que se puedan romper

**Comment by camilonova** [comment]
Not anymoar
